### ISSUE TITLE
error while launching it

### ISSUE THREAD

**Issue by Righted1** [TheDreamFoxy/GDCommentBot#1]
i'm always getting a error while launching the program.

error message:
Error: Cannot find module 'request'
Require stack:
- C:\Users\stefa\OneDrive\Bureau\GDCommentBot-main\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:974:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (C:\Users\stefa\OneDrive\Bureau\GDCommentBot-main\index.js:1:17)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Users\\stefa\\OneDrive\\Bureau\\GDCommentBot-main\\index.js'←[39m ]
}

**Comment by doxyf** [comment]
You have to install the libraries first.
use `npm i` or if it won't help, use `npm i request`
